# Generated by Django 3.1.7 on 2021-05-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_sentenze', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='permission',
        ),
        migrations.AddField(
            model_name='profile',
            name='permission',
            field=models.ManyToManyField(to='tag_sentenze.Sentenza'),
        ),
    ]
