# Generated by Django 3.1.7 on 2021-05-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_sentenze', '0001_initial'),
        ('users', '0002_auto_20210509_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='permission',
            field=models.ManyToManyField(blank=True, to='tag_sentenze.Sentenza'),
        ),
    ]
