# Generated by Django 3.2 on 2021-04-29 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sentenza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, unique=True)),
                ('sentenza', models.FileField(help_text='Scegli la sentenza da taggare.', upload_to='uploads/')),
                ('schema_xml', models.FileField(help_text='Scegli il file xml da utilizzare.', upload_to='uploads/')),
                ('completed', models.BooleanField(default=False)),
                ('testo_iniziale', models.TextField(blank=True)),
                ('testo_taggato_html', models.TextField(blank=True)),
                ('testo_taggato_xml', models.TextField(blank=True)),
            ],
        ),
    ]
