# Generated by Django 3.1.6 on 2021-03-21 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag_sentenze', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentenza',
            old_name='upload',
            new_name='sentenza',
        ),
    ]
