# Generated by Django 3.1.6 on 2021-03-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_sentenze', '0002_auto_20210321_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentenza',
            name='sentenza',
            field=models.FileField(help_text='Scegli la sentenza da taggare.', upload_to='uploads/'),
        ),
    ]
