# Generated by Django 3.1.7 on 2021-03-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_sentenze', '0003_auto_20210321_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visualizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
    ]
