# Generated by Django 3.1.7 on 2021-03-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_sentenze', '0004_visualizer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visualizer',
        ),
        migrations.AddField(
            model_name='sentenza',
            name='xml_schema',
            field=models.FileField(help_text='Scegli il file xml da utilizzare.', null=True, upload_to='uploads/'),
        ),
    ]
