# Generated by Django 3.1.7 on 2021-03-28 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag_sentenze', '0004_visualizer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visualizer',
        ),
    ]
