# Generated by Django 3.1.7 on 2021-04-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_sentenze', '0005_auto_20210329_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentenza',
            name='nome',
            field=models.CharField(default='Sentenza', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
