# Generated by Django 3.1.7 on 2021-03-29 12:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tag_sentenze', '0005_delete_visualizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentenza',
            name='output_xml',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='sentenza',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
