# Generated by Django 3.1.7 on 2021-03-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_sentenze', '0008_auto_20210329_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentenza',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
