# Generated by Django 3.1.7 on 2021-03-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_sentenze', '0009_auto_20210329_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentenza',
            name='output_xml',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='sentenza',
            name='title',
            field=models.CharField(default='ciao', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
