# Generated by Django 3.1.7 on 2021-03-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_sentenze', '0010_auto_20210329_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentenza',
            name='output_xml',
            field=models.FileField(blank=True, default='wo', upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
