# Generated by Django 3.1.7 on 2021-03-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_sentenze', '0013_auto_20210329_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentenza',
            name='output_xml',
            field=models.CharField(blank=True, max_length=10000000),
        ),
    ]
