# Generated by Django 3.1.7 on 2021-03-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_sentenze', '0015_auto_20210329_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentenza',
            name='output_xml',
            field=models.TextField(blank=True),
        ),
    ]
