# Generated by Django 3.1.7 on 2021-04-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_sentenze', '0016_auto_20210329_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentenza',
            name='intial_text',
            field=models.TextField(blank=True),
        ),
    ]
