# Generated by Django 3.2 on 2021-04-18 16:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tag_sentenze', '0018_auto_20210402_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentenza',
            name='completed',
            field=models.BooleanField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sentenza',
            name='xml_schema',
            field=models.FileField(help_text='Scegli il file xml da utilizzare.', null=True, upload_to='uploads/'),
        ),
    ]
