# Generated by Django 3.2 on 2021-04-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_sentenze', '0019_auto_20210418_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentenza',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
