# Generated by Django 3.2 on 2021-04-18 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag_sentenze', '0020_alter_sentenza_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentenza',
            old_name='xml_schema',
            new_name='schema_xml',
        ),
    ]
