# Generated by Django 3.2 on 2021-04-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_sentenze', '0021_rename_xml_schema_sentenza_schema_xml'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentenza',
            old_name='initial_text',
            new_name='testo_iniziale',
        ),
        migrations.RenameField(
            model_name='sentenza',
            old_name='output_xml',
            new_name='testo_taggato_html',
        ),
        migrations.AddField(
            model_name='sentenza',
            name='testo_taggato_xml',
            field=models.TextField(blank=True),
        ),
    ]
