# Generated by Django 3.2 on 2021-04-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_sentenze', '0022_auto_20210418_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentenza',
            name='schema_xml',
            field=models.FileField(help_text='Scegli il file xml da utilizzare.', upload_to='uploads/'),
        ),
    ]
